### ISSUE TITLE
Fiche site - Liste des visites - Renommer "Taxons" en "Nb de taxons"

### ISSUE THREAD

**Issue by camillemonchicourt** [PnCevennes/projet_suivi#13]

**Comment by fdonfi** [comment]
Finalement ce sera richesse

**Comment by amandine-sahl** [comment]
Ajouter champs : Somme des individus dénombrés et l'appeler Abondance

**Comment by camillemonchicourt** [comment]
Pas sur que ça soit super clair .
Ça me parle qu'a moitié. Notamment la notion de "richesse" ?
Nombre de taxons et nombre d'individus.
