### ISSUE TITLE
Fiches détails - Ajouter des bordures à chaque attribut avec couleurs alternées

### ISSUE THREAD

**Issue by camillemonchicourt** [PnCevennes/projet_suivi#20]

**Comment by camillemonchicourt** [comment]
![fiche](https://cloud.githubusercontent.com/assets/4418840/8130909/e479972e-1116-11e5-800f-d0072cf4d3eb.jpg)

**Comment by amandine-sahl** [comment]
https://docs.angularjs.org/api/ng/directive/ngClassEven
