### ISSUE TITLE
BUG - Lignes colorées dans la liste des sites

### ISSUE THREAD

**Issue by camillemonchicourt** [PnCevennes/projet_suivi#30]
Quand je clique sur un site dans la liste, la ligne se colore en VERT. 
Si je clique sur un autre, le précédent reste coloré en VERT.

**Comment by camillemonchicourt** [comment]
Réglé à priori ? 
Close ?

**Comment by camillemonchicourt** [comment]
Reste un bug quand je vais sur la fiche d'un site, puis retourne sur la liste. Le site que je viens de visiter reste sélectionné.

**Comment by fdonfi** [comment]
Le bug initial est résolu. Ce rapport sera automatiquement fermé (enfin normalement) lorsque la branche sera fusionnée avec le master.

Pour le second bug, ce n'en est pas un, c'est le comportement souhaité. C'est pas bien comme ça ?

**Comment by camillemonchicourt** [comment]
OK ! 
Pour le second, pourquoi pas que la fiche visitée reste selectionnée quand on revient sur la liste. Mais elle devrait se déselectionner dès que je clique sur une autre ligne.

**Comment by fdonfi** [comment]
C'est pas ce qui se passe ?

**Comment by camillemonchicourt** [comment]
Non le site visité précédemment reste sélectionné..

**Comment by fdonfi** [comment]
tu as mis à jour depuis la branche dev ?

**Comment by camillemonchicourt** [comment]
Non je teste sur votre serveur.

**Comment by amandine-sahl** [comment]
C'est bon, je viens de mettre le serveur à jour

Le 23 juin 2015 11:28, Camille Monchicourt notifications@github.com a
écrit :

**Comment by camillemonchicourt** [comment]
OK, bingo !
