### ISSUE TITLE
nouvelle visite - nouvel un observateur. il ne se passe rien quand on clique sur les 3 petits points

### ISSUE THREAD

**Issue by gildeluermoz** [PnCevennes/projet_suivi#34]

**Comment by gildeluermoz** [comment]
Il ne se passe rien quand on clique sur les 3 petits points à droite de la liste déroulante.
L'auto complétion n'est pas intuitive. Du coup, par exemple, on ne peut pas savoir qui est présent ou pas dans la liste

**Comment by amandine-sahl** [comment]
Pour l'autocomplétion je ne sais pas, peut être qu'un tooltip suffirait. Sinon les trois points on disparu.
