### ISSUE TITLE
Aménagement - impossible de consulter les fichiers joints

### ISSUE THREAD

**Issue by gildeluermoz** [PnCevennes/projet_suivi#43]
Si on clique sur le lien vers le fichier : 
"Oops! An Error Occurred
The server returned a "404 Not Found".
Something is broken. Please let us know what you were doing when this error occurred. We will fix it as soon as possible. Sorry for any inconvenience caused. "

**Comment by amandine-sahl** [comment]
Du a des transferts brutaux de BD
